version: "3.7"

services:
  # 데이터베이스
    database-mysql :
      restart: always
      container_name: database-mysql
      image: tjseocld/mysql:8.0.29
      command: 
      #- 'mysqld --default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      #volumes:
      #  - ./my.cnf:/etc/my.cnf
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mystory
        TZ: Asia/Seoul
      volumes:
        - ./mysql-init.d:/docker-entrypoint-initdb.d
      ports:
        - '13306:3306'
      

  # 서버
    server-springBoot :
      restart: always
      container_name: server-springBoot
      depends_on:
        - database-mysql
        - client-react
      image: tjseocld/tomcat:9.0.64
      build: ./mystory
      ports:
        - '18080:8080'

 # 클라이언트
    client-react :
      restart: always
      container_name: client-react
      image: tjseocld/mystory:latest
      build: ./frontend
      volumes:
        - "./frontend:/app"
        - "/app/node_modules"
      ports:
        - "3000:3000"
      #environment:
      #  - NODE_ENV=development
      #stdin_open: true
      #tty: true 
