version: "3.7"

services:
# 젠킨스
    jenkins:
      container_name: jenkins
      build:
        context: .
        dockerfile: ./Dockerfile
      image: jenkins/jenkins:lts-jdk11
      ports:
        - 18080:8080
      volumes:
        - ./jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      environment: 
            TZ: "Asia/Seoul"