client:
  url: http://localhost:3000
server:
  url: http://localhost:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mystory?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#  sql:
#    init:
#      mode: always
#      platform: dev

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-secret: sn7W5EVI1B
            client-id: KrgceyS11oJLy_u0tajR
            client-name: naver
          kakao:
            client-id: 7cef126b7f8ea367330765d225a271a6
            client-secret: unknown
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname , account_email
            client-name: kakao
          google:
            client-id: 468391770326-850l305qj81ah6s9j2irhfqvsiupnkgk.apps.googleusercontent.com
            client-secret: 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
            scope: email , profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token

logging:
  level:
    org:
      springframework:
        security: DEBUG

cloud:
  aws:
    s3:
      bucket: mystory50-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA375CYUSRLLSCEUGM
      secretKey: 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