version: "3.7"

services:
  # 데이터베이스
    db:
      container_name: myStoryMysql
      image: mysql:latest
      restart: always
      command: mysqld --default-authentication-plugin=mysql_native_password
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: myStory
      ports:
        - '3306:3306'

  # 서버
    web:
      container_name: tomcatServer
      restart: always
      links:
        - db
      image: tomcat:8.0
      volumes:
        - ./ROOT.war:/usr/local/tomcat/webapps/ROOT.war
      ports:
        - '8080:8080'

 # 클라이언트
    client:
      restart: always
      container_name: client
      links:
        - web
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ".:/app"
        - "/app/node_modules"
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      stdin_open: true
      tty: true 